### ISSUE TITLE
Support final states with equal particles

### ISSUE THREAD

**Issue by redeboer** [ComPWA/ampform-dpd#108]
This requires keeping track of state IDs in the `Particle` class.

**Comment by mmikhasenko** [comment]
Xib2pK-K-

There is LHCb paper with DPD

**Comment by mmikhasenko** [comment]
Looks great!

 - How do you know if symmetrization is done correctly. I remember there are non-trivial permutation properties for helicity couplings due to pK vs Kpi in chains?

 - Do you reproduce the fit fractions?
![image](https://github.com/ComPWA/ampform-dpd/assets/22725744/c2dedac9-e31c-4ace-a73c-13f11ced05a2)

if you can compute this matrix for any arbitrary couplings, it is possible to recover the right couplings by comparing the two tables

**Comment by mmikhasenko** [comment]
sounds good
